app:
  image: tutum/hello-world:latest
  environment:
    SERVICE_NAME: app
    SERVICE_TAGS: production
  ports:
  - "80"

lb:
  build: ./
  links:
  - consul
  ports:
  - "80:80"

consul:
  command: -server -bootstrap -advertise 192.168.2.139 
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

registrator:
  command: consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
